### ISSUE TITLE
example

### ISSUE THREAD

**Issue by fcuencaML** [debezium/debezium-examples#18]
in this example (mysql) where can i found the broker, group and topic . To consume kafka from outside?
Thanks !

**Comment by jpechane** [comment]
Broker is running on port `9092` on the localhost interface of the machine where the example is run.
Group is set by consumer and there is no relation between consumer group and our example. It can be arbitrary string.
Topic is in format `<server-name>.<database-name>.<table-name>` as visible in example that demostrates consuming from the queue.

**Comment by gunnarmorling** [comment]
Hi @fcuencaML, also take a look at _docker-compose_mysql.json_ for more details (e.g. ports of other services). If you're running on Docker for Mac, you also must set `ADVERTISED_HOST_NAME` to your host machine's name when connecting from the same, [as described](http://debezium.io/docs/faq/#how_to_connect_to_kafka_when_using_the_debezium_docker_images) in our FAQ.

Can you please report back if that helps so this issue can be closed? For questions, it's generally better to come to our [Google Group](https://groups.google.com/forum/#!forum/debezium), that way any answers are more easily findable by others, too. Thanks!

**Comment by fcuencaML** [comment]
Hi there @gunnarmorling !, i want to consume kafka topic from outside containers . how can i set the correct hostname inside the docker-compose.yml ?. I read about it, and i found that i can set an environment variable like this : 

environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_HOST_NAME= {{HOSTNAME}}

{{HOSTNAME}} corresponds to docker or my machine (using mac)? .

**Comment by gunnarmorling** [comment]
Going to close this one, as the question should better be asked on our [mailing list](https://groups.google.com/forum/#!forum/debezium). Also see the FAQ on the website regarding the Docke question. Thanks!
