### ISSUE TITLE
hi,i cant use debezium-embedded to receive new update dbmessage.....

### ISSUE THREAD

**Issue by myseed** [debezium/debezium-examples#19]
hi,this is my first time to study debezium ,i want use debezium-embedded to receive mysql message,but,only first time ,i can receive the db message.after this ,i update the mysql table,no message send to me.this is my java coding.

public static void main(String[] args) throws IOException{
		Configuration config = Configuration.create()
                .with("connector.class",
                      "io.debezium.connector.mysql.MySqlConnector")
                .with("offset.storage",
                      "org.apache.kafka.connect.storage.FileOffsetBackingStore")
                .with("offset.storage.file.filename","/path/to/storage/offset58127r.dat")
                .with("name", "my-sql-connector")
                .with("database.hostname", "192.168.50.88")
                .with("database.port", 3310)
                .with("database.user", "appuser")
                .with("database.password", "appuser123")
                .with("server.id", 255579)
                .with("database.server.name", "my-app-connector")
                .with("database.history",
                      "io.debezium.relational.history.FileDatabaseHistory")
                .with("database.history.file.filename",
                      "/path/to/storage/dbhistory71.dat")
                .build();
		Consumer<SourceRecord> con=new ConsumerDota();
                //Create the engine with this configuration ...
                EmbeddedEngine engine = EmbeddedEngine.create()
                  .using(config)
                  .notifying(con)
                  .build();
                BlockingQueue<Runnable> queue = new ArrayBlockingQueue<Runnable>(
        				50);
        		ThreadPoolExecutor threadPool = new ThreadPoolExecutor(1500, 1500, 50000L,
        				TimeUnit.MILLISECONDS, queue);
        		threadPool.setRejectedExecutionHandler(new RejectedExecutionHandler() {

        			public void rejectedExecution(Runnable r,
        					ThreadPoolExecutor executor) {
        				try {  					
        					executor.getQueue().put(r);
        				} catch (InterruptedException e) {
        					e.printStackTrace();
        				}
        			}
        		});
        		threadPool.execute(engine);
        		System.in.read();
                engine.stop();

what's wrong.....
thank you

**Comment by jpechane** [comment]
Hi, I think this is better to move to our chat room (https://gitter.im/debezium/user) for a discussion. Also it would be great if you enable `DEBUG` logging (http://debezium.io/docs/configuration/logging/#debezium_loggers) for the whole `io.debezium` package so we can look at what's going on.

**Comment by gunnarmorling** [comment]
Going to close this one, as the question should better be asked on our [mailing list](https://groups.google.com/forum/#!forum/debezium). Thanks!
