### ISSUE TITLE
issue while running while Start MongoDB sink connector,can any one suggest me how can i resolve

### ISSUE THREAD

**Issue by siva2krish** [debezium/debezium-examples#26]
$ curl -i -X POST -H "Accept:application/json" -H  "Content-Type:application/json" http://localhost:8084/connectors/ -d @mongodb-sink.json

{"error_code":500,"message":"Failed to find any class that implements Connector and which name matches at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector, available connectors are: PluginDesc{klass=class io.debezium.connector.mongodb.MongoDbConnector, name='io.debezium.connector.mongodb.MongoDbConnector', version='0.9.0.Alpha1', encodedVersion=0.9.0.Alpha1, type=source, typeName='source', location='file:/kafka/connect/debezium-connector-mongodb/'}, PluginDesc{klass=class io.debezium.connector.mysql.MySqlConnector, name='io.debezium.connector.mysql.MySqlConnector', version='0.9.0.Alpha1', encodedVersion=0.9.0.Alpha1, type=source, typeName='source', location='file:/kafka/connect/debezium-connector-mysql/'}, PluginDesc{klass=class io.debezium.connector.oracle.OracleConnector, name='io.debezium.connector.oracle.OracleConnector', version='0.9.0.Alpha1', encodedVersion=0.9.0.Alpha1, type=source, typeName='source', location='file:/kafka/connect/debezium-connector-oracle/'}, PluginDesc{klass=class io.debezium.connector.postgresql.PostgresConnector, name='io.debezium.connector.postgresql.PostgresConnector', version='0.9.0.Alpha1', encodedVersion=0.9.0.Alpha1, type=source, typeName='source', location='file:/kafka/connect/debezium-connector-postgres/'}, PluginDesc{klass=class io.debezium.connector.sqlserver.SqlServerConnector, name='io.debezium.connector.sqlserver.SqlServerConnector', version='0.9.0.Alpha1', encodedVersion=0.9.0.Alpha1, type=source, typeName='source', location='file:/kafka/connect/debezium-connector-sqlserver/'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='1.1.1', encodedVersion=1.1.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='1.1.1', encodedVersion=1.1.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='1.1.1', encodedVersion=1.1.1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='1.1.1', encodedVersion=1.1.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='1.1.1', encodedVersion=1.1.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='1.1.1', encodedVersion=1.1.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='1.1.1', encodedVersion=1.1.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='1.1.1', encodedVersion=1.1.1, type=source, typeName='source', location='classpath'}"}

**Comment by gunnarmorling** [comment]
You must add the MongoDB sink connector to the plug-ins directory of Kafka Connect.

**Comment by gunnarmorling** [comment]
Going to close this one, as it seems addressed and questions should better be asked on our [mailing list](https://groups.google.com/forum/#!forum/debezium). Thanks!
