### ISSUE TITLE
Postgres - whitelist

### ISSUE THREAD

**Issue by yonigibbs** [debezium/debezium-examples#34]
In the [register-postgres.json](https://github.com/debezium/debezium-examples/blob/master/tutorial/register-postgres.json) file in the tutorial, this line exists:

`"database.whitelist": "inventory"`

However, in the [documentation for the Postgres connector](https://debezium.io/docs/connectors/postgresql/) there is no mention of `database.whitelist`.  There is only `schema.whitelist` and `table.whitelist`.

If you get a chance, it might be worth fixing this slight discrepancy to clarify which of the whitelist values is allowed for this connector.

Thanks.

**Comment by jpechane** [comment]
Thanks for spotting! It is indeed `schema.whitelist`. This work now because the database contains only this schema.

**Comment by gunnarmorling** [comment]
Good catch. Fixed it. Thanks!
