### ISSUE TITLE
Please publish the debezium-jdbc-es docker image

### ISSUE THREAD

**Issue by mingfang** [debezium/debezium-examples#41]
I think this image is actually very useful for non-example use cases since many people would want to sink to elasticsearch

**Comment by mingfang** [comment]
@gunnarmorling I agree with everything you said, and yes I can and usually do build my own images.
But I think another reason to publish debezium-jdbc-es is to make this example work https://debezium.io/blog/2018/01/17/streaming-to-elasticsearch/.  Currently the debezium-kafka, zookeeper, mysql and connect has been publish but this one is missing.

**Comment by mingfang** [comment]
For now I built the debezium-jdbc-es image pushed to my own repo.
Also I built a set of terraform modules to run the example here https://github.com/mingfang/terraform-provider-k8s/tree/master/solutions/debezium

**Comment by gunnarmorling** [comment]
Closing this one, as it seems resolved. Interesting work with the Terraform set-up; are you doing it just as an exercise/example? Are you going to blog about it? Ah, and btw. you might find strimzi.io interesting, which is a K8S Operator for setting up Kafka and Connect.

Thanks!
