### ISSUE TITLE
some observations on your recent blog-post ref streaming data

### ISSUE THREAD

**Issue by Analect** [debezium/debezium-examples#5]
@jpechane 
I was working through your recent blog-post ...http://debezium.io/blog/2017/09/25/streaming-to-another-database/ ... thanks for that.  There were a few problems I was coming up against, which I thought I might highlight to you here.

I was using it as an opportunity to run things in a kubernetes context ... rather than using docker-compose and it mostly works.

I think the example presumes that the image `debezium/connect-jdbc:${DEBEZIUM_VERSION}` (I used 0.6 for DEBEZIUM_VERSION) exists on the docker registry ... but I don't think it does.  You may need to instruct users to generated their own based on the [Dockerfile](https://github.com/debezium/debezium-examples/blob/master/unwrap-smt/debezium-jdbc/Dockerfile) or push your generated version to the debezium registry.

With things set up and appearing to work  ... I then ran through aspects of the [debezium tutorial](http://debezium.io/docs/tutorial/) you link to in the blog ... essentially adding new records and updating existing ones ... and observing these changes getting captured in the postgres sink database.

However, when it came to deleting a record in mySQL ... this deletion did not get captured in postgres and I just wanted a better understanding of why that might be.  Is it something to do with your [jdbc-sink](https://github.com/debezium/debezium-examples/blob/master/unwrap-smt/jdbc-sink.json) settings that might prevent the delete operation from taking effect in postgres?  Below are the messages that get generated to the `customers` topic for an UPDATE and then a DELETE ... the update works fine (in terms of getting reflected in postgres), the delete doesn't.

```
{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"first_name"},{"type":"string","optional":false,"field":"last_name"},{"type":"string","optional":false,"field":"email"}],"optional":true,"name":"dbserver1.inventory.customers.Value","field":"before"},{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"first_name"},{"type":"string","optional":false,"field":"last_name"},{"type":"string","optional":false,"field":"email"}],"optional":true,"name":"dbserver1.inventory.customers.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"server_id"},{"type":"int64","optional":false,"field":"ts_sec"},{"type":"string","optional":true,"field":"gtid"},{"type":"string","optional":false,"field":"file"},{"type":"int64","optional":false,"field":"pos"},{"type":"int32","optional":false,"field":"row"},{"type":"boolean","optional":true,"field":"snapshot"},{"type":"int64","optional":true,"field":"thread"},{"type":"string","optional":true,"field":"db"},{"type":"string","optional":true,"field":"table"}],"optional":false,"name":"io.debezium.connector.mysql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"}],"optional":false,"name":"dbserver1.inventory.customers.Envelope","version":1},"payload":{"before":{"id":1004,"first_name":"Anne","last_name":"Kretchmar","email":"annek@noanswer.org"},"after":{"id":1004,"first_name":"Anne Marie","last_name":"Kretchmar","email":"annek@noanswer.org"},"source":{"name":"dbserver1","server_id":223344,"ts_sec":1506960312,"gtid":null,"file":"mysql-bin.000003","pos":986,"row":0,"snapshot":null,"thread":14,"db":"inventory","table":"customers"},"op":"u","ts_ms":1506960312130}}
{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"first_name"},{"type":"string","optional":false,"field":"last_name"},{"type":"string","optional":false,"field":"email"}],"optional":true,"name":"dbserver1.inventory.customers.Value","field":"before"},{"type":"struct","fields":[{"type":"int32","optional":false,"field":"id"},{"type":"string","optional":false,"field":"first_name"},{"type":"string","optional":false,"field":"last_name"},{"type":"string","optional":false,"field":"email"}],"optional":true,"name":"dbserver1.inventory.customers.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"server_id"},{"type":"int64","optional":false,"field":"ts_sec"},{"type":"string","optional":true,"field":"gtid"},{"type":"string","optional":false,"field":"file"},{"type":"int64","optional":false,"field":"pos"},{"type":"int32","optional":false,"field":"row"},{"type":"boolean","optional":true,"field":"snapshot"},{"type":"int64","optional":true,"field":"thread"},{"type":"string","optional":true,"field":"db"},{"type":"string","optional":true,"field":"table"}],"optional":false,"name":"io.debezium.connector.mysql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"}],"optional":false,"name":"dbserver1.inventory.customers.Envelope","version":1},"payload":{"before":{"id":1004,"first_name":"Anne Marie","last_name":"Kretchmar","email":"annek@noanswer.org"},"after":null,"source":{"name":"dbserver1","server_id":223344,"ts_sec":1506960381,"gtid":null,"file":"mysql-bin.000003","pos":1347,"row":0,"snapshot":null,"thread":15,"db":"inventory","table":"customers"},"op":"d","ts_ms":1506960381842}}
{"schema":null,"payload":null}
```
If you think there's value in adding a new folder to this repo to run through the basics of getting this up-and-running on kubernetes, I can try to create a PR.

**Comment by Analect** [comment]
OK ... I see the confluent kafka-connect-jdbc sink isn't set up to handle deletes ... but that this [PR](
https://github.com/confluentinc/kafka-connect-jdbc/pull/282) is intended to fix that.  My understanding is that the debezium postgres connector is just for use as a source rather than a sink.  Is that the case?

**Comment by rhauch** [comment]
The Debezium connectors are all source connectors.

**Comment by jpechane** [comment]
Hi,

you are right - the image does not exist. It is built locally on the fly by Docker Compose. But I'll highlight it in the example repo README.md.

I'd be glad if you preapre a Kubernetes PR. Just please look at [this PR](https://github.com/debezium/debezium-examples/pull/6) intended for OpensShift. It is possible we will not use Debezium images to run on k8s but will reuse instead images from project [enmasse](https://github.com/EnMasseProject/barnabas).

**Comment by gunnarmorling** [comment]
Closing this one. Regarding running Debezium on Kubernetes and related distros such as OpenShift, I recommend to take a look at the Strimzi project (strimzi.io), which provides images and more interestingly, K8S Operators for setting up everything quite easily.
